### ISSUE TITLE
detect other locations of QnA

### ISSUE THREAD

**Issue by jgstew** [rustymyers/QnAGUI#2]
This is a minor thing, not an immediate request.

It would be interesting to look for QnA in other locations like the Applications folder like it used to exist in the past, as well as the locations that Matt's AutoPkg install recipe puts it.

I think it makes sense to prefer the QnA bundled with the BigFix agent if it exists, otherwise it would probably check each location until it finds one. Bonus points would be if it could detect the newest version of QnA available on the system.

**Comment by jgstew** [comment]
**Related:** https://github.com/rustymyers/QnAGUI/issues/3#issuecomment-266548330

It would be useful if `QnA GUI` gave feedback on any issues invoking QnA as well as a way to click/hover something to figure out where it is using QnA from.

**Comment by rustymyers** [comment]
How many other locations would it be worth checking? /usr/local/bin might have a QnA, but would or should it ever be used if it's outside /Library/BESAgent/BESAgent.app/Contents/MacOS/? 

Searching all files might take some time, but searching a couple directories would be quick.

I've added a tool tip to the Query button that shows the path of the QnA binary being used. Will be released in next update.

**Comment by rustymyers** [comment]
Re-reading the original post, we could check for ['/Applications/', '/usr/local/bin/', and '/Library/BESAgent/' for QnA binaries. I'm unsure how to check their versions though. If we can determine each version then we could pick the latest one.

**Comment by jgstew** [comment]
See the `get_path_QNA():` found here: https://github.com/jgstew/EvaluateRelevance.py/blob/master/EvaluateRelevance.py#L16

My approach there is to attempt them in an order of preference, returning the first valid one found, starting with the current working directory, then `/usr/local/bin`, and so on. In my case I'm assuming that if you have one in the current working directory, then that is the one you want to use, same with `/usr/local/bin`. This approach also allows for cross platform use of the function by including the OS specific locations at the end.

Being able to get the versions would be handy, but not strictly needed in most cases. I'm not sure if there is any easy way to get the version WITHOUT running the query `version of client`

You can actually find the version in the file using the `strings` but it is an ugly option:

`strings /Library/BESAgent/BESAgent.app/Contents/MacOS/QnA | grep "9.5.14.73"`

This seems to work in the general case, but not certain it will always return 1 result:

`strings /Library/BESAgent/BESAgent.app/Contents/MacOS/QnA | grep -E '\d+(\.\d+){3}'`

It should be possible to do this parsing directly within swift or python in a cross platform way without the need to use `strings` or `grep`

I'm not sure if there is a better option, but I don't think MacOS has typical built in metadata for binaries in the same way that Windows does and I don't think there is an associated `Info.plist` that could be used in all cases either.

**Comment by jgstew** [comment]
This issue is resolved by: https://github.com/rustymyers/QnAGUI/commit/9cc2c7bb1282afaa58002c0b1a1369a04a9d202f
