### ISSUE TITLE
add recovery for last run relevance query

### ISSUE THREAD

**Issue by jgstew** [rustymyers/QnAGUI#7]
just before running a relevance query through QnAGUI, save a copy of the query to be run to `/tmp/_QnA_GUI_relevance.txt` or similar so that if I ask a relevance query that takes forever to return, that I can still recover my last query if I have to force quit the app.

Next level would be on start of the app, load the last query from that file if it exists.

I have a bad habit of accidentally asking unanswerable questions of relevance when testing.

**Comment by rustymyers** [comment]
Released in v1.5

**Comment by jgstew** [comment]
this feature just saved me.
